---
version: "3"

env:
  ANSIBLE_CONFIG: "{{.USER_WORKING_DIR}}/ansible.cfg"

vars:
  ANSIBLE_ARGS: '{{default "" .ANSIBLE_ARGS}}'

tasks:
  facts:
    desc: "Retrieve facts about a host"
    cmds:
      - ansible {{.CLI_ARGS}} -m ansible.builtin.setup

  galaxy:
    desc: "Install roles and collections from Ansible Galaxy"
    cmds:
      - task: galaxy:clean
      - ansible-galaxy collection install -p {{.USER_WORKING_DIR}}/collections -r {{.USER_WORKING_DIR}}/requirements.yml
      - ansible-galaxy role install -p {{.USER_WORKING_DIR}}/roles_galaxy -r {{.USER_WORKING_DIR}}/requirements.yml

  galaxy:clean:
    desc: "Clean roles and collections installed from Ansible Galaxy"
    cmds:
      - rm -rf {{.USER_WORKING_DIR}}/roles_galaxy/*
      - rm -rf {{.USER_WORKING_DIR}}/collections/*

  galaxy:force:
    desc: "Force install roles and collections from Ansible Galaxy"
    cmds:
      - task: galaxy:clean
      - ansible-galaxy collection install -f -p {{.USER_WORKING_DIR}}/collections -r {{.USER_WORKING_DIR}}/requirements.yml
      - ansible-galaxy role install -f -p {{.USER_WORKING_DIR}}/roles_galaxy -r {{.USER_WORKING_DIR}}/requirements.yml

  install:
    desc: "Install dependencies"
    cmds:
      - pip install -r requirements.txt
      - task: galaxy

  inventory:
    desc: "List all inventory hosts"
    cmds:
      - ansible-inventory --graph {{.CLI_ARGS}}

  inventory:plugins:
    desc: "List all inventory plugins"
    cmds:
      - ansible-doc -t inventory -l

  lint:
    desc: "Check syntax"
    cmds:
      - ansible-lint *

  ping:
    desc: "Ping all nodes"
    cmds:
      - ansible --one-line -m ping

  playbook:
    desc: "Run an Ansible playbook"
    cmds:
      - ansible-playbook {{.ANSIBLE_ARGS}} {{.CLI_ARGS}}

  playbook:debug:
    desc: "Run an Ansible playbook with maximum debugging"
    cmds:
      - ansible-playbook -vvvv {{.ANSIBLE_ARGS}} {{.CLI_ARGS}}

