---
version: '3'

includes:
  ansible:
    taskfile: ./ansible.tasks.yml
  
  docker:
    taskfile: ./docker.yml

  git:
    taskfile: ./git.tasks.yml

  internals:
    taskfile: ./internals.tasks.yml

  packer:
    taskfile: ./packer.tasks.yml

  rclone:
    taskfile: ./rclone.tasks.yml
  
  shellcheck:
    taskfile: ./shellcheck.tasks.yml

  ssh:
    taskfile: ./ssh.tasks.yml

  terraform:
    taskfile: ./terraform.tasks.yml

tasks:
  default:
    cmds:
      - task: internals:task_search
    silent: true
